### ISSUE TITLE
add grouping bars for each of the labels

### ISSUE THREAD

**Issue by jkanche** [epiviz/epiviz.heatmap.gl#2]

**Comment by zoecastillo** [comment]
If unclear, this should look similar to how R packages such as heatmaply are doing this. 

Colors should be an optional parameter or if not specified revert to a default palette (Kana has a range in its utils).
A set of around 10-12 colors is sufficient falling back on random ones if more are needed.

A legend for the colorbar should be shown with options to specify location in relation to the heatmap/grouping bar.

**Comment by zoecastillo** [comment]
@OssamaRafique This page has some examples for both the legends as well as the grouping bars (row/column side colors): [heatmaply](https://talgalili.github.io/heatmaply/articles/heatmaply.html)
I don't consider this style to be the most aesthetically pleasing, so no need to replicate the exact look. But hopefully this helps to understand the scope of what we want to do.
