### ISSUE TITLE
Add legend of intensity

### ISSUE THREAD

**Issue by zoecastillo** [epiviz/epiviz.heatmap.gl#4]
We need a legend showing the color values used in the heatmap.
In most cases, these will be continuous showing a bar-gradient with numerical values at intervals.
Placement of the legend relative to the heatmap should be adjustable (top, botton, left, right).

Legend should be shown on demand.
Legend needs to share space with groupbar legends, so rules to avoid overlap and optimize overall layout will be required.

**Comment by OssamaRafique** [comment]
Done #14
