### ISSUE TITLE
Add selections of multiple rows/cols

### ISSUE THREAD

**Issue by zoecastillo** [epiviz/epiviz.heatmap.gl#8]
Following the process of click-selecting a single row/col, selecting multiple rows/cols via brush-selection should be possible.
All selected rows/columns should be returned and selected region should be highlighted.

**Comment by jkanche** [comment]
@OssamaRafique I just noticed the state is not being reset somewhere properly, to reproduce this issue

Step 1: click on "enable highlight", select a few columns/rows, I clicked on C9-11 and r4-6
<img width="440" alt="image" src="https://github.com/epiviz/epiviz.heatmap.gl/assets/399324/260c2ef4-746e-4bb3-9522-383c3e6a8675">

Step 2: clear highlights by clicking the button

<img width="231" alt="image" src="https://github.com/epiviz/epiviz.heatmap.gl/assets/399324/36fb80f5-4d7d-48b4-a14b-e17ddde910e8">

Step 3: try to highlgiht the same rows from Step 1, I would have to double click on the labels. for others single-click works.

**Comment by OssamaRafique** [comment]
@jkanche Thanks for pointing this out, PR is up #13

**Comment by jkanche** [comment]
Thanks for the update
